name: Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    uses: teh-hippo/common-repo-configs/.github/workflows/mdbook.yml@a09e52c265474981aa190ed3997bdc59e7e7ed56  # v3.0.0
    permissions:
      pages: write
      id-token: write
      contents: read
    with:
      path: docs
