name: Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    uses: teh-hippo/common-repo-configs/.github/workflows/mdbook.yml@04bf429c2e0e2bf5b325665f1d03c5a79137e0e3  # v3.2.10
    permissions:
      pages: write
      id-token: write
      contents: read
    with:
      path: docs
