name: Release Please

on:
  push:
    branches: [main]

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    uses: teh-hippo/common-repo-configs/.github/workflows/release-please.yml@c931fba4d72479caec16ca097b7ce105aa56ede4 # v1
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
