name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    uses: teh-hippo/common-repo-configs/.github/workflows/release-please.yml@942482e4a5c6c04b2cedf484c8cbd7e186365619  # v3.2.34
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
