name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    uses: teh-hippo/common-repo-configs/.github/workflows/release-please.yml@04bf429c2e0e2bf5b325665f1d03c5a79137e0e3  # v3.2.10
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
